### ISSUE TITLE
tutorial 2

### ISSUE THREAD

**Issue by Annsas** [LukeTheHecker/esinet#10]
ValueError: Sequential model 'FC-model' has already been configured to use input shape (None, None, 203). You cannot build it with input_shape (None, 203)

**Comment by LukeTheHecker** [comment]
Thanks for the notification! Can you please provide the code that produced this error?

**Comment by Annsas** [comment]
> Thanks for the notification! Can you please provide the code that produced this error?

It has been solved ,thank you
