### ISSUE TITLE
Interpolate step

### ISSUE THREAD

**Issue by tPPMc-cs** [LukeTheHecker/esinet#4]

**Comment by tPPMc-cs** [comment]
What is the process of interpolate the raw data into a 7x11 matrix?^_^

**Comment by LukeTheHecker** [comment]
Hey, please refer to the following lines of code, hopefully this answers your question:

https://github.com/LukeTheHecker/esinet/blob/1d76ce818f9494ede8e3cb06acda71010e391a89/esinet/net.py#L242

Otherwise feel free to come back to the issue later!
