### ISSUE TITLE
pandas no longer supports .append() for DataFrames (replace with concat) 

### ISSUE THREAD

**Issue by johnkylecooper** [LukeTheHecker/esinet#9]
I ran into an error with pandas on line 392 of `simulation.py` within the `simulate_source` function. I see that at one time there was an intention to either use `append` or `concat`, but now that `append` is deprecated `concat` is necessary. The line should be changed from:
```
self.simulation_info = self.simulation_info.append(d, ignore_index=True)
```
to
```
self.simulation_info = pd.concat([self.simulation_info, pd.DataFrame([d])], ignore_index=True)
```
Best,
JKC

**Comment by LukeTheHecker** [comment]
Thank you ver much, I think this issue has been resolved.
